apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-backend
  namespace: weather
  labels:
    app: weather-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weather-backend
  template:
    metadata:
      name: weather-backend
      labels:
        app: weather-backend
    spec:
      containers:
        - name: weather-backend
          image: localhost:32000/weather-backend:v1
          imagePullPolicy: IfNotPresent
          env:
            - name: OPEN_METEO_BASE_URL
              value: "https://api.open-meteo.com"
            - name: MIN_LATITUDE
              value: "-90"
            - name: MAX_LATITUDE
              value: "90"
            - name: MIN_LONGITUDE
              value: "-180"
            - name: MAX_LONGITUDE
              value: "180"
            - name: INSTALLATION_POWER_KW
              value: "2.5"
            - name: INSTALLATION_EFFICIENCY
              value: "0.2"
            - name: PRODUCTION
              value: "1"
      restartPolicy: Always